{% set pkgname = "python-confluent-kafka" %}
{% set name = "confluent-kafka" %}
{% set version = "0.11.5ci_test3" %}
{% set sha256hash = "90b0fbe4ed85a12d3643309a021b1125f32be5a59d78cac5c4d016defe465876" %}

package:
  name: {{ pkgname|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/confluentinc/confluent-kafka-python/archive/v{{ version }}.tar.gz
  sha256: {{ sha256hash }}

build:
  number: 0
  # There is no win build for librdkafka at this time.
  skip: True  # [win]

requirements:
  build:
    - toolchain
    - python
    - setuptools
    - librdkafka >=0.11.0,<0.12
  run:
    - python
    - librdkafka >=0.11.0,<0.12

test:
  imports:
    - confluent_kafka

  commands:
    - conda inspect linkages {{ pkgname }}  # [unix]
    - conda inspect objects {{ pkgname }}   # [osx]

about:
  home: https://github.com/confluentinc/confluent-kafka-python
  license: Apache 2.0
  license_file: LICENSE.txt
  summary: "Confluent's Apache Kafka client for Python"
  description: |
    Confluent's Kafka client for Python wraps the librdkafka C library,
    providing full Kafka protocol support with great performance and
    reliability.
  doc_url: http://docs.confluent.io/current/clients/confluent-kafka-python/index.html

extra:
  recipe-maintainers:
    - rmax
    - mrocklin
