{% set pkgname = "python-confluent-kafka" %}
{% set name = "confluent-kafka" %}
{% set version = "2.5.0-2" %}

package:
  name: {{ pkgname|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/confluentinc/confluent-kafka-python/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 1ab342bd5340e6cb18988424232c036a8cb2cc936eab9836f11b1603c506ca8e
  patches:
    - 0001-Fix-setup-for-windows.patch  # [win]

build:
  # This package does not support PyPy.
  # See https://github.com/confluentinc/confluent-kafka-python/issues/1747#issuecomment-2112004625
  skip: true  # [python_impl == 'pypy']
  number: 0
  script:
    - export CFLAGS="${CFLAGS} -I${PREFIX}/include"  # [unix]
    - export LDFLAGS="${LDFLAGS} -I${PREFIX}/lib"    # [unix]
    - set CFLAGS="%CFLAGS% /I%LIBRARY_INC%"          # [win]
    - set LDFLAGS="%LDFLAGS% /I%LIBRARY_LIB%"        # [win]
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - setuptools
    - pip
    - librdkafka >={{ version }}
  run:
    - python
    - librdkafka >={{ version }}

test:
  imports:
    - confluent_kafka

about:
  home: https://github.com/confluentinc/confluent-kafka-python
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: Confluent's Apache Kafka client for Python
  description: |
    Confluent's Kafka client for Python wraps the librdkafka C library,
    providing full Kafka protocol support with great performance and
    reliability.
  doc_url: http://docs.confluent.io/current/clients/confluent-kafka-python/index.html

extra:
  recipe-maintainers:
    - lpsinger
    - rmax
    - mrocklin
    - mariusvniekerk
    - duncanmmacleod
